version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: sys
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    networks:
      - springmysql-net
    volumes:
      - db:/var/lib/mysql    
      

 

  backcommune-services:
    container_name: backcommune
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/database?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sys
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    networks:
      - springmysql-net

volumes:
    db:

networks:
  springmysql-net:


